import 'package:flutter/material.dart';
import 'package:flutterapp/taskapp/generatedtask_page_1widget/generated/GeneratedTask_model_during2Widget1.dart';
import 'package:flutterapp/taskapp/generatedtask_page_1widget/generated/GeneratedTask_model_during2Widget2.dart';
import 'package:flutterapp/taskapp/generatedtask_page_1widget/generated/GeneratedChange_pageWidget6.dart';
import 'package:flutterapp/taskapp/generatedtask_page_1widget/generated/GeneratedNavigationBarWidget2.dart';
import 'package:flutterapp/taskapp/generatedtask_page_1widget/generated/GeneratedTask_model_during2Widget.dart';

/* Frame task_page_1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTask_page_1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 390.0,
              height: 844.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 6.0,
                      top: 210.0,
                      right: null,
                      bottom: null,
                      width: 378.0,
                      height: 182.0,
                      child: GeneratedTask_model_during2Widget(),
                    ),
                    Positioned(
                      left: 5.0,
                      top: 422.0,
                      right: null,
                      bottom: null,
                      width: 378.0,
                      height: 182.0,
                      child: GeneratedTask_model_during2Widget1(),
                    ),
                    Positioned(
                      left: 7.0,
                      top: 634.0,
                      right: null,
                      bottom: null,
                      width: 378.0,
                      height: 182.0,
                      child: GeneratedTask_model_during2Widget2(),
                    )
                  ]),
            ),
            Positioned(
              left: 20.0,
              top: 100.0,
              right: null,
              bottom: null,
              width: 350.0,
              height: 50.0,
              child: GeneratedChange_pageWidget6(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 390.0,
              height: 90.0,
              child: GeneratedNavigationBarWidget2(),
            )
          ]),
    ));
  }
}
