import 'package:flutter/material.dart';
import 'package:flutterapp/taskapp/generatedtask_page_3widget/generated/GeneratedNavigationBarWidget1.dart';
import 'package:flutterapp/taskapp/generatedtask_page_3widget/generated/GeneratedChange_pageWidget3.dart';
import 'package:flutterapp/taskapp/generatedtask_page_3widget/generated/GeneratedFrame5Widget1.dart';

/* Frame task_page_3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTask_page_3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 390.0,
              height: 844.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 180.0,
                      right: null,
                      bottom: null,
                      width: 130.0,
                      height: 40.0,
                      child: GeneratedFrame5Widget1(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 390.0,
              height: 90.0,
              child: GeneratedNavigationBarWidget1(),
            ),
            Positioned(
              left: 20.0,
              top: 110.0,
              right: null,
              bottom: null,
              width: 350.0,
              height: 50.0,
              child: GeneratedChange_pageWidget3(),
            )
          ]),
    ));
  }
}
