import 'package:flutter/material.dart';
import 'package:flutterapp/newoceanapp/generated_widget2/generated/GeneratedNo5Widget.dart';
import 'package:flutterapp/newoceanapp/generated_widget2/generated/GeneratedNo7Widget.dart';
import 'package:flutterapp/newoceanapp/generated_widget2/generated/GeneratedNavigationBarWidget2.dart';
import 'package:flutterapp/newoceanapp/generated_widget2/generated/GeneratedNo1Widget.dart';
import 'package:flutterapp/newoceanapp/generated_widget2/generated/GeneratedChange_pageWidget3.dart';
import 'package:flutterapp/newoceanapp/generated_widget2/generated/GeneratedNo2Widget.dart';

/* Frame 動物圖鑑_已解鎖
    Autogenerated by FlutLab FTF Generator
  */
class Generated_Widget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 187.0,
                top: 392.0,
                right: null,
                bottom: null,
                width: 144.0,
                height: 191.0,
                child: GeneratedNo7Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 392.0,
                right: null,
                bottom: null,
                width: 144.0,
                height: 195.0,
                child: GeneratedNo5Widget(),
              ),
              Positioned(
                left: 180.0,
                top: 194.0,
                right: null,
                bottom: null,
                width: 144.0,
                height: 206.0,
                child: GeneratedNo2Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 194.0,
                right: null,
                bottom: null,
                width: 144.0,
                height: 206.0,
                child: GeneratedNo1Widget(),
              ),
              Positioned(
                left: 2.0,
                top: 102.0,
                right: null,
                bottom: null,
                width: 350.0,
                height: 50.0,
                child: GeneratedChange_pageWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 90.0,
                child: GeneratedNavigationBarWidget2(),
              )
            ]),
      ),
    ));
  }
}
