// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDStuRqec_PpIUi11V6gjqmEAxRfDz6vLk',
    appId: '1:223238297413:web:2bcd0fe7f784ccaeadd02c',
    messagingSenderId: '223238297413',
    projectId: 'newocean-444d7',
    authDomain: 'newocean-444d7.firebaseapp.com',
    databaseURL: 'https://newocean-444d7-default-rtdb.firebaseio.com',
    storageBucket: 'newocean-444d7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5YMWqrWbkkxqhP6du3SeyvXIRuXBSiqs',
    appId: '1:223238297413:android:f77ea9e53ffc2df4add02c',
    messagingSenderId: '223238297413',
    projectId: 'newocean-444d7',
    databaseURL: 'https://newocean-444d7-default-rtdb.firebaseio.com',
    storageBucket: 'newocean-444d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB914tdgMtvNt4F72Ce5DE0Fb30rY23wnU',
    appId: '1:223238297413:ios:14fb797b52328d1eadd02c',
    messagingSenderId: '223238297413',
    projectId: 'newocean-444d7',
    databaseURL: 'https://newocean-444d7-default-rtdb.firebaseio.com',
    storageBucket: 'newocean-444d7.appspot.com',
    iosClientId: '223238297413-a97pm4iffs4hl2i2bs2mac1gcsoa8opv.apps.googleusercontent.com',
    iosBundleId: 'com.fcu.newocean',
  );
}
