import 'package:flutter/material.dart';
import 'package:flutterapp/newoceanapp/generated_widget/generated/GeneratedWidget13.dart';
import 'package:flutterapp/newoceanapp/generated_widget/generated/GeneratedWidget18.dart';
import 'package:flutterapp/newoceanapp/generated_widget/generated/GeneratedFbWidget.dart';
import 'package:flutterapp/newoceanapp/generated_widget/generated/GeneratedWidget.dart';
import 'package:flutterapp/newoceanapp/generated_widget/generated/GeneratedNavigationBarWidget.dart';

/* Frame 動物互動_主頁
    Autogenerated by FlutLab FTF Generator
  */
class Generated_Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 176, 226, 217),
                ),
              ),
              Positioned(
                left: 10.0,
                top: 621.0,
                right: null,
                bottom: null,
                width: 350.0,
                height: 164.0,
                child: GeneratedWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 474.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 135.0,
                child: GeneratedWidget13(),
              ),
              Positioned(
                left: 268.0,
                top: 418.0,
                right: null,
                bottom: null,
                width: 75.27906799316406,
                height: 39.0,
                child: GeneratedFbWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 107.0,
                right: null,
                bottom: null,
                width: 350.0,
                height: 350.0,
                child: GeneratedWidget18(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 90.0,
                child: GeneratedNavigationBarWidget(),
              )
            ]),
      ),
    ));
  }
}
