import 'package:flutter/material.dart';
import 'package:flutterapp/newoceanapp/generated_widget1/generated/GeneratedNo4Widget.dart';
import 'package:flutterapp/newoceanapp/generated_widget1/generated/GeneratedNo8Widget.dart';
import 'package:flutterapp/newoceanapp/generated_widget1/generated/GeneratedNavigationBarWidget1.dart';
import 'package:flutterapp/newoceanapp/generated_widget1/generated/GeneratedChange_pageWidget.dart';
import 'package:flutterapp/newoceanapp/generated_widget1/generated/GeneratedNo6Widget.dart';
import 'package:flutterapp/newoceanapp/generated_widget1/generated/GeneratedNo3Widget.dart';

/* Frame 動物圖鑑_未解鎖
    Autogenerated by FlutLab FTF Generator
  */
class Generated_Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 159.0,
                top: 393.0,
                right: null,
                bottom: null,
                width: 205.0,
                height: 195.0,
                child: GeneratedNo8Widget(),
              ),
              Positioned(
                left: -3.0,
                top: 397.0,
                right: null,
                bottom: null,
                width: 205.0,
                height: 195.0,
                child: GeneratedNo6Widget(),
              ),
              Positioned(
                left: 159.0,
                top: 190.0,
                right: null,
                bottom: null,
                width: 205.0,
                height: 194.0,
                child: GeneratedNo4Widget(),
              ),
              Positioned(
                left: -5.0,
                top: 190.0,
                right: null,
                bottom: null,
                width: 205.0,
                height: 207.0,
                child: GeneratedNo3Widget(),
              ),
              Positioned(
                left: 5.0,
                top: 103.0,
                right: null,
                bottom: null,
                width: 350.5,
                height: 50.0,
                child: GeneratedChange_pageWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 90.0,
                child: GeneratedNavigationBarWidget1(),
              )
            ]),
      ),
    ));
  }
}
