import 'package:flutter/material.dart';
import 'package:flutterapp/taskapp/generatedtask_page_2widget/generated/GeneratedChange_pageWidget.dart';
import 'package:flutterapp/taskapp/generatedtask_page_2widget/generated/GeneratedFrame5Widget.dart';
import 'package:flutterapp/taskapp/generatedtask_page_2widget/generated/GeneratedFrame3Widget.dart';
import 'package:flutterapp/taskapp/generatedtask_page_2widget/generated/GeneratedFrame6Widget.dart';
import 'package:flutterapp/taskapp/generatedtask_page_2widget/generated/GeneratedNavigationBarWidget.dart';

import '../../img_try.dart';

/* Frame task_page_2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTask_page_2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 390.0,
              height: 844.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 25.0,
                      top: 500.0,
                      right: null,
                      bottom: null,
                      width: 341.0,
                      height: 177.0,
                      child: SwiperPic(title: '這是輪播圖'),
                    ),
                    Positioned(
                      left: 25.0,
                      top: 240.0,
                      right: null,
                      bottom: null,
                      width: 341.0,
                      height: 177.0,
                      child: GeneratedFrame3Widget(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 180.0,
                      right: null,
                      bottom: null,
                      width: 120.0,
                      height: 40.0,
                      child: GeneratedFrame5Widget(),
                    ),
                    Positioned(
                      left: 134.0,
                      top: 411.0,
                      right: null,
                      bottom: null,
                      width: 107.0,
                      height: 24.77191162109375,
                      child: GeneratedFrame6Widget(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 390.0,
              height: 90.0,
              child: GeneratedNavigationBarWidget(),
            ),
            Positioned(
              left: 20.0,
              top: 110.0,
              right: null,
              bottom: null,
              width: 350.0,
              height: 50.0,
              child: GeneratedChange_pageWidget(),
            )
          ]),
    ));
  }
}
